### ISSUE TITLE
Stop all the services with one tag

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-ansible#109]
**Is your feature request related to a problem? Please describe.**

By default, the recipe stop.yml doesn't stop httpd, postgresl and monitoring. If I would like to shut down these services, I have to add option '--tasks never'. But adding this option, prevents to shut down the other services of ESGF (tomcat, cog, etc.) when managing a set of data, idp and index nodes. The solution is quite straightforward : add --tags "data,idp,index,never" to shut down all the services of a set of data, idp and index nodes. But esgf-ansible may implement new services in the future and I don't want to miss to stop these services.

**Describe the solution you'd like**

So I would like a tag that makes all the services to stop, whenever esgf-ansible will add new services.

**Describe alternatives you've considered**

Any other mechanism that aims the same goal.

**Additional context**

**Comment by nathanlcarlson** [comment]
Hmmm, I believe `--tags "all, never"` could work. `all` is a special tag, like `never`.

There is more info here https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html if you would like all the information about tags.

**Comment by gardoll** [comment]
It works ! Thank !
