### ISSUE TITLE
Replica shards disappear from CoG after 4.0.3 upgrade.

### ISSUE THREAD

**Issue by glevava** [ESGF/esgf-ansible#110]
**Describe the bug**
After trying to upgrade our production node (esgf-node.ipsl.upmc.fr) from 2.6.7 to 4.0.3.
CoF Data Searches and the search API itself doesn't return any data from the replica shards.
esgf_shards_static.xml and other configuration files and CoG seetings have been checked without any changes.

Note that the upgrade failed first when cloning the CoG repository. We had to force it using "force :yes" in the appropriate ansible roles.
Then the node is upgraded and starts correctly. But the whole CoG config was reset and we observe that the "TestProject" build by default redirects to the LIU node instead of IPSL which is really strange behavior.
 
**To Reproduce**
From ESGF 2.6.7 : 
`ansible-playbook -i hosts.prod -u root --skip-tags gridftp --tags 'index,idp' --limit esgf-node.ipsl.upmc.fr install.yml`

**Expected behavior**
Having the node installed with legacy CoG configuration and project pages. Also replica shards always accessible.

**ESGF Node (please complete the following information):**
 - Managed OS: CentOS 6
 - Host OS: CentOS 6
 - esgf-ansible Version: 4.0.3
 - Node type: Index (full node)

**Additional context**

**Comment by gardoll** [comment]
the log file.
[upgrade.log](https://github.com/ESGF/esgf-ansible/files/3355820/upgrade.log)

**Comment by nathanlcarlson** [comment]
Hi, as GK mentioned and you already implemented, a fix for this is staged and is going to be included in the next release. The above commit 1fe0c9b  was made because I thought the issue may be unrelated. I will leave this open until the next release.

**Comment by nathanlcarlson** [comment]
Included in release 4.0.4
