### ISSUE TITLE
Restart playbook

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#122]
If I need to stop and start services, this needs to be issued in 2 commands.  This is not great because (1) the stop may complete and leave the node offline for the time it takes me to notice, or I have to watch it for the period.  (2) for remote Sudo I have to enter credentials twice.  That would make calling both playbooks in a script impractical.  Could the playbooks be wrapped into a single restart.yml, hopefully preserving order?

**Comment by nathanlcarlson** [comment]
I think I've pointed this out some places, but my current practice is the following:
```
$ ansible-playbook [ args ] stop.yml start.yml [ status.yml ]
```
This will queue up the two playbooks `stop.yml` and `start.yml` to run with one authentication prompt. Optionally tack on `status.yml` to check if services came up correctly.

**Comment by nathanlcarlson** [comment]
Going to close this because I believe the above is an adequate solution.
