### ISSUE TITLE
Using CI tests with travis

### ISSUE THREAD

**Issue by cehbrecht** [ESGF/esgf-ansible#53]
It would be nice to have continuous-integration tests (on Travis or others) to see if the default deployment is still working.

Here are some examples how to use Travis CI for Ansible playbook testing with docker containers:
* https://github.com/geerlingguy/ansible-role-nginx/blob/master/.travis.yml
* https://github.com/ANXS/postgresql/blob/master/.travis.yml

The nginx role is using molecule:
https://pypi.org/project/molecule/

**Comment by nathanlcarlson** [comment]
@cehbrecht  We are using Jenkins as our automation and testing server at LLNL. We test some simple and some more complicated deployments.

The definition of a "working" deployment is fairly complicated. Many issues with the deployments may not become apparent until after the deployment is complete and the node goes into operation. Also, deployments are nearly always done on a machine that is in some unknown state that is the result of years of previous deployments and manual admin operations. These two factors make it difficult to have a simple CI pipeline that says whether or not the deployment is "working".
