### ISSUE TITLE
Private keys / certs on local vs remote machines

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#56]
I have generated a CSR first time running the installer.  I got it signed, great, but what to do now?  Looks like I need to copy the private key back to my local machine in order to specify in the hosts variables file.  In order to do that I need to make it readable by non-root user.  Maybe thats ok...but not great practice for private keys....

How about instead of single variables we have local vs remote - we should be clear: "local" is the client, ie. your laptop?

gftphostcert_local: /home/ames4/esgf-data-node.pem
gftphostkey_remote:  /root/gridftp.key

In this example we mix and match a remote key (where it was generated, and a .key extension might be helpful) with a signed cert (from the CSR) on my local system.  While Prashanth has been putting CSRs responses on his website for download (with wget) may not be a universal practice, so remote or local options might be handy.  For instance our web-certs are received by email, but private keys remain on the remote system.

**Comment by gardoll** [comment]
I agree with Sasha about disambiguating the variable names. Plus, I would prefer a lot that keys and certificates never leave their host.

**Comment by nathanlcarlson** [comment]
The changes made to resolve this can be found in #68. While the changes are are somewhat restrictive to the user, it provides enhanced reliability. The user likely values something reliable over something that is slightly more convenient.
