### ISSUE TITLE
esgf-config repo still present

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#64]
It appears that if installation fails at some point, a clone of the esgf-config repo is left in /tmp with modifications that causes a subsequent clone to fail:

```TASK [base : Clone ESGF config repository] *************************************
task path: /Users/ames4/git-repos/esgf-ansible/roles/base/tasks/config.yml:2
fatal: [esgf-test-data.llnl.gov]: FAILED! => {
    "before": "c62d6d576374263a375bf1b1436527cb7b618052",
    "changed": false
}

MSG:

Local modifications exist in repository (force=no).


PLAY RECAP *********************************************************************
esgf-test-data.llnl.gov    : ok=78   changed=7    unreachable=0    failed=1
```

This might be hard to reproduce.  If the repo isn't need perhaps the best option is to delete it so nothing is left behind

I had used devel with the most recent commit: ff088ae73d342d502

**Comment by nathanlcarlson** [comment]
I think it would be reasonable to set `force: yes` ?

**Comment by nathanlcarlson** [comment]
This repo will get force written to `/tmp`. The `.xml` files in `/esg/config` are **not** force written. So if a `.xml` file is already in place there, it is not overwritten.
