### ISSUE TITLE
update CoG 

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#67]
The version of CoG deployed with Ansible is out-of-date.   Is the change in the @William-Hill William-Hill fork still necessary?  I don't remember if this was only needed for Python (ESGFv3) If so we should merge into CoG devel and create a new tag.

**Comment by nathanlcarlson** [comment]
I think it would be worth while to make a pull request from the fork to the main devel branch. There are some changes that I believe should be merged in and may require looking at more closely.

**Comment by sashakames** [comment]
PR already exists.  https://github.com/EarthSystemCoG/COG/pull/1396
I noticed that SQLAlchemy and pscopg2 lose their versions specs.  We should probably put in the same constraints being applied to other modules.

**Comment by sashakames** [comment]
https://github.com/earthsystemcog/COG
v3.14.0

**Comment by nathanlcarlson** [comment]
Going to close this as it is now being tested and will be a part of the next release.
