### ISSUE TITLE
Upgrade to esg-publisher 3.7.0 ; add call to esgfetchini -k

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#71]
esg-publisher will be updated to 3.7.0.  This will remove the calls to esgfetchini and esgprep in setup.py effectively decoupling the modules.  
To accommodate this, a call to `esgfetchini -k` should be made by the playbook prior to esgsetup is run.  That call depends on esgprep installed in the environment.  For now same `esgf-pub` as esgcet, but may consider changing near future.

**Comment by nathanlcarlson** [comment]
Included in release 4.0.4
