### ISSUE TITLE
Install trusted certificates for Globus: FAIL

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#73]
**Describe the bug**
The following failed:  fatal: [esgf-test-data.llnl.gov]: FAILED! => {
    "changed": true,
    "cmd": "cp /tmp/esg_trusted_certificates/* /etc/grid-security/certificates",
    "delta": "0:00:00.006249",
    "end": "2019-03-25 11:02:05.553235",
    "rc": 1,
    "start": "2019-03-25 11:02:05.546986"
}

STDERR:

cp: cannot stat `/tmp/esg_trusted_certificates/*': No such file or directory

MSG:

non-zero return code

Merged from devel branch latest commit: d89c6433968

**Comment by nathanlcarlson** [comment]
Hi @sashakames,
What does the task prior to it say? This isn't the first time this machine has had something strange happen in /tmp, referring to the /tmp/esgf-config issue #64.

**Comment by nathanlcarlson** [comment]
I've made the above change in #74. Not sure why the files in your `/tmp` keep getting cleaned out.

**Comment by sashakames** [comment]
here's the previous task:  TASK [globus_certs : Copy globus hostkey into place] ***********************************************
ok: [esgf-test-data.llnl.gov] => {
    "changed": false,
    "checksum": "3e8b5eb751a54f0151037666abf32b3ed255b65b",
    "dest": "/etc/grid-security/hostkey.pem",
    "gid": 0,
    "group": "root",
    "md5sum": "034a2fab354e310039db37655c0d5b36",
    "mode": "0600",
    "owner": "root",
    "size": 6720,
    "src": "/tmp/esgf-test-data-hostcert.pem",
    "state": "file",
    "uid": 0
}

**Comment by nathanlcarlson** [comment]
Okay so what seems to have happened is that the directory `/tmp/esg_trusted_certificates` still exists, but something emptied it. Because the directory still exists, prior to #74, the download would not happen. Now it is setup to always re-download the `.tar` an extract it there.

**Comment by nathanlcarlson** [comment]
@sashakames I'd recommend pulling the new changes and running again.  I will close this issue after confirming it does not happen again.
