### ISSUE TITLE
inconsistent webapps after upgrading legacy installation

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-ansible#90]
**Describe the bug**

After a successful upgrade of a legacy installation, orp, idp, esgf-search and thredds webapps don't start. catalina.out shows some inconsistency like:

* Orp & idp
Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema or spring-security-3.2.xsd schema with Spring Security 4.0. Please update your schema declarations to the 4.0 schema.
Offending resource: class path resource [esg/orp/orp/config/security-context-auth.xml]
* thredds
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/thredds]]

Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.util.LoaderUtil.isClassAvailable(Ljava/lang/String;)

**To Reproduce**

Upgrade a v2.6.7-master-release node  with esgf-ansible 4.0.2

**ESGF Node (please complete the following information):**
 - Managed OS: CentOS 6
 - Host OS: CentOS 7
 - esgf-ansible Version: v4.0.2
 - Node type: upgrading idp, index and data nodes

**Workaround**

Simply delete the webapps before upgrading a legacy installation and probably esgf-ansi should always do that.

rm -fr /usr/local/tomcat/webapps/*
rm -fr /usr/local/src

**Comment by nathanlcarlson** [comment]
Created and merged #92  to address this. Tomcat web apps will always be cleaned out and reinstalled.
