### ISSUE TITLE
Add playbook to set up a Prometheus query crontab

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-ansible#96]
We are integrating node status information into CoG and need the backend to support that.
(1) Playbook should either fetch the repo or create an environment that runs the "query_prom.py" CLI
(2) Add a crontab to call a shell script that can activate the environment and call the python script with proper items.  Need to agree on the frequency (how many minutes) and set cron accordingly

**Comment by nathanlcarlson** [comment]
Going to close this since the playbook is set to be in the next release
